### ISSUE TITLE
It doesn't work in Python 2.7

### ISSUE THREAD

**Issue by RoberWare** [kivy-garden/garden.joystick#6]
I don't know why this occurs.
`
[INFO              ] [Logger      ] Record log in /home/roberto/.kivy/logs/kivy_17-09-11_34.txt
[INFO              ] [Kivy        ] v1.9.0
[INFO              ] [Python      ] v2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
[INFO              ] [Factory     ] 173 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
 /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
   set_interactive(1)
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <4.5.0 NVIDIA 375.66>
[INFO              ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO              ] [GL          ] OpenGL renderer <GeForce GT 620/PCIe/SSE2>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <4.50 NVIDIA>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [GL          ] NPOT texture support is available
[ERROR             ] [Image       ] Error reading file ./imgs/logo.png
[INFO              ] [VideoGstplayer] Using Gstreamer 1.8.3.0
[INFO              ] [Video       ] Provider: gstplayer
 Traceback (most recent call last):
   File "/home/roberto/Programas/Python/VideoPad/main.py", line 76, in <module>
     MainApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 798, in run
     root = self.build()
   File "/home/roberto/Programas/Python/VideoPad/main.py", line 57, in build
     self.myMetaPanel = MetaPanel()
   File "/usr/lib/python2.7/dist-packages/kivy/uix/boxlayout.py", line 102, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/layout.py", line 66, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 271, in __init__
     Builder.apply(self)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1872, in apply
     self._apply_rule(widget, rule, rule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1986, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1985, in _apply_rule
     self.apply(child)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1872, in apply
     self._apply_rule(widget, rule, rule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1986, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1986, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1985, in _apply_rule
     self.apply(child)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1872, in apply
     self._apply_rule(widget, rule, rule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1986, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1986, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1985, in _apply_rule
     self.apply(child)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1872, in apply
     self._apply_rule(widget, rule, rule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1984, in _apply_rule
     widget.add_widget(child)
   File "/home/roberto/Programas/Python/VideoPad/libs/garden/garden.joystick/joystick/joystick.py", line 184, in add_widget
     super().add_widget(widget)
 TypeError: super() takes at least 1 argument (0 given)
`
I just added the Joystick widget inside of a screen in this way:
`
<VideoPadUI>
    BoxLayout:
        orientation: "vertical"
        Video:
            id: video
            source: "http://root:toor@192.168.0.167:8080/video"
            play: True
    FloatLayout:
        size: root.size
        BoxLayout:
            Joystick:
                sticky: False
                outer_size: 1
                inner_size: 0.75
                pad_size:   0.5
                outer_line_width: 0.01
                inner_line_width: 0.01
                pad_line_width:   0.01
                outer_background_color: (0.75, 0.75, 0.75, 0.3)
                outer_line_color:       (0.25, 0.25, 0.25, 0.3)
                inner_background_color: (0.75, 0.75, 0.75, 0.1)
                inner_line_color:       (0.7,  0.7,  0.7,  0.1)
                pad_background_color:   (0.4,  0.4,  0.4,  0.3)
                pad_line_color:         (0.35, 0.35, 0.35, 0.3)
`

I tried JoystickDemo.py and it runs but a black screen is showed.

**Comment by Narcolapser** [comment]
I see the problem. It's related to a python2 vs python3 compatibility issue. I'll try to fix it later today or tomorrow. 

https://stackoverflow.com/questions/38963018/typeerror-super-takes-at-least-1-argument-0-given-error-is-specific-to-any

Try running your app in python3 and see if it makes any difference.

**Comment by RoberWare** [comment]
Thanks for reply!.
I'll try to run it in python3. It would be great if you fix that.

**Comment by Narcolapser** [comment]
ok, now that we know the problem for sure, I'll try to fix it tonight.

**Comment by susheel-smrt** [comment]
Is there any fix to run this joystick on python 2.7?

**Comment by Narcolapser** [comment]
Yes, I believe I have just fixed it, give it a try and let me know if it works for you all.

**Comment by RoberWare** [comment]
It works perfectly!, thanks for the quick fix!!

**Comment by susheel-selvamani** [comment]
Still I am not able to run it on python 2.x console. I'm getting following error.

```
[ERROR  ] Error while activating FileHandler logger
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kivy/logger.py", line 225, in emit
    self._configure()
  File "/usr/lib/python2.7/dist-packages/kivy/logger.py", line 183, in _configure
    FileHandler.fd = open(filename, 'w')
IOError: [Errno 13] Permission denied: u'/home/susheel/.kivy/logs/kivy_17-09-14_0.txt'
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 17.0.7>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Haswell Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "/home/susheel/Downloads/garden.joystick-master/example/JoystickDemo.py", line 42, in <module>
     JoystickDemoApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 802, in run
     root = self.build()
   File "/home/susheel/Downloads/garden.joystick-master/example/JoystickDemo.py", line 14, in build
     self.root = JoystickDemo()
   File "/usr/lib/python2.7/dist-packages/kivy/uix/floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 345, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 451, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 566, in _apply_rule
     self.apply(child)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 451, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 566, in _apply_rule
     self.apply(child)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 451, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 565, in _apply_rule
     widget.add_widget(child)
   File "/home/susheel/.kivy/garden/garden.joystick/joystick/joystick.py", line 184, in add_widget
     super().add_widget(widget)
 TypeError: super() takes at least 1 argument (0 given)

```

**Comment by Narcolapser** [comment]
I see this at the end: 

```
File "/home/susheel/.kivy/garden/garden.joystick/joystick/joystick.py", line 184, in add_widget
super().add_widget(widget)
TypeError: super() takes at least 1 argument (0 given)
```

That is the exact error I fixed, that line, 184, now looks like [this](https://github.com/kivy-garden/garden.joystick/blob/master/joystick/joystick.py#L184). It would seem the changes didn't get into your local garden instance. Try refreshing the code, by hand if necessary, so that it uses the latest version.

**Comment by susheel-selvamani** [comment]
Bro, I verified the code actually.. It's exactly as you directed.. though I'm getting the error. I'm attaching the line 184 below.
######################################
def add_widget(self, widget):
        super(Joystick, self).add_widget(widget) #line184
        self.do_layout()

**Comment by Narcolapser** [comment]
Then it some how isn't picking it up. Check this file: 

    /home/susheel/.kivy/garden/garden.joystick/joystick/joystick.py
