### ISSUE TITLE
[ERROR] Invalid width value, must be > 0

### ISSUE THREAD

**Issue by electricalgorithm** [kivy-garden/garden.joystick#7]
@Narcolapser
Error on console:
```bash
[INFO   ] [Logger      ] Record log in C:\Users\gokha\.kivy\logs\kivy_20-08-13_37.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\gokha\PycharmProjects\invdef\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\gokha\PycharmProjects\invdef\venv\Scripts\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 26.20.100.7637'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics 630'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 26.20.100.7637'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:/Users/gokha/PycharmProjects/invdef/main.py", line 66, in <module>
     MainApp().run()
   File "C:\Users\gokha\PycharmProjects\invdef\venv\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\gokha\PycharmProjects\invdef\venv\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\gokha\PycharmProjects\invdef\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\gokha\PycharmProjects\invdef\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\gokha\PycharmProjects\invdef\venv\lib\site-packages\kivy\base.py", line 345, in idle
     Builder.sync()
   File "C:\Users\gokha\PycharmProjects\invdef\venv\lib\site-packages\kivy\lang\builder.py", line 788, in sync
     call_fn(next_args[:-1], None, None)
   File "C:\Users\gokha\PycharmProjects\invdef\venv\lib\site-packages\kivy\lang\builder.py", line 76, in call_fn
     setattr(element, key, e_value)
   File "kivy\graphics\vertex_instructions_line.pxi", line 782, in kivy.graphics.vertex_instructions.Line.width.__set__
 kivy.graphics.vertex_instructions.GraphicException: Invalid width value, must be > 0

Process finished with exit code 1
```

main.py:
```python

# -*- coding: utf-8 -*-
from kivy.lang import Builder
from kivymd.app import MDApp
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.properties import ObjectProperty
from kivymd.toast import toast
from joystick import Joystick

# Variable Declaration from KV File
username = ObjectProperty(None)
passwordd = ObjectProperty(None)


class MainWindow(Screen):

    def check_user(self):
        if self.username.text == "2elec" and self.passwordd.text == "12345":
            self.passwordd.text = ""
            return 1
        else:
            self.username.text = ""
            self.passwordd.text = ""
            toast("Wrong password or username. Try again.")
            return 0


class AdminPanel(Screen):

    def coordinates(self):
        toast("27.489523, 32.127835")
        return 0


class WinManager(ScreenManager):
    pass


class MainApp(MDApp):
    def __init__(self, **kwargs):
        self.theme_cls.primary_palette = "Teal"
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_hue = "500"
        self.title = "IUC Thermoelectricity Laboratuary"
        super().__init__(**kwargs)

    def build(self):
        self.root = Builder.load_file("template.kv")
        self._bind_joysticks()

    def _bind_joysticks(self):
        joysticks = self._get_joysticks(self.root)
        for joystick in joysticks:
            joystick.bind(pad=self._update_pad_display)

    def _get_joysticks(self, parent):
        joysticks = []
        if isinstance(parent, Joystick):
            joysticks.append(parent)
        elif hasattr(parent, 'children'):
            for child in parent.children:
                joysticks.extend(self._get_joysticks(child))
        return joysticks


if __name__ == "__main__":
    MainApp().run()
```

template.kv:
```kivy
#:import CardTransition kivy.uix.screenmanager.CardTransition
#:import OneLineIconListItem kivymd.uix.list
#:import MDList kivymd.uix.list
#:import IconRightWidget kivymd.uix.list
#:import Joystick joystick
#:import MDTooltip kivymd.uix.tooltip

<TooltipMDIconButton@MDIconButton+MDTooltip>

WinManager:
    transition: CardTransition()
    MainWindow:
        name: "loginPanel"
    AdminPanel:
        name: "adminPanel"

<MainWindow>:
    username: usernameID
    passwordd: passwordID
    MDCard:
        orientation: "vertical"
        padding: "20dp"
        spacing: 20
        size_hint: None, None
        size: "300dp", "350dp"
        pos_hint: {"center_x": .5, "center_y": .5}

        MDLabel:
            text: "IUC Thermoelectricty Laboratuary"
            theme_text_color: "Primary"
            halign: "center"
            font_style: "H4"
            size_hint_y: None
            height: self.texture_size[1]

        MDBoxLayout:
            orientation: "vertical"
            spacing: "5dp"
            adaptive_height: True

            MDTextField:
                id: usernameID
                hint_text: "Username"
                helper_text: "Type your username to access admin panel."
                helper_text_mode: "on_focus"
                multiline: False

            MDTextField:
                id: passwordID
                hint_text: "Password"
                password: True
                multiline: False

        MDRaisedButton:
            text: "Get In"
            text_color: 1,1,1,1
            md_bg_color: .33, .33, .33, 1
            pos_hint: {"center_x": .5, "center_y": .5}
            on_release:
                app.root.current = "adminPanel" if root.check_user() else "loginPanel"
                root.manager.transition.direction = "up"

<AdminPanel>:
    BoxLayout:
        orientation: "horizontal"
        md_bg_color: app.theme_cls.primary_color

        MDGridLayout:
            rows: 5
            adaptive_width: True
            md_bg_color: app.theme_cls.primary_color

            TooltipMDIconButton:
                icon: "menu-open"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Access Menu"
            TooltipMDIconButton:
                icon: "coolant-temperature"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Temperature Shield"
            TooltipMDIconButton:
                icon: "signal-off"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Jammer"
            TooltipMDIconButton:
                icon: "car-light-high"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Car Light"
            TooltipMDIconButton:
                icon: "near-me"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Car Engine"

        Button:
            text: "live video here"
        GridLayout:
            size_hint_x: 0.3
            rows: 2
            BoxLayout:
                orientation: "vertical"
                md_bg_color: app.theme_cls.primary_color
                MDList:
                    OneLineIconListItem:
                        text: "23'C"
                        IconLeftWidget:
                            icon: "weather-sunny"
                    OneLineIconListItem:
                        text: "47'C"
                        IconLeftWidget:
                            icon: "car-defrost-rear"
                    OneLineIconListItem:
                        text: "W 5 m/s"
                        IconLeftWidget:
                            icon: "weather-windy"
                    OneLineIconListItem:
                        text: "70 km/h"
                        IconLeftWidget:
                            icon: "speedometer"
                    OneLineIconListItem:
                        text: "Coordinates"
                        on_release: root.coordinates()
                        IconLeftWidget:
                            icon: "crosshairs-gps"

            BoxLayout:
                Joystick:
                    outer_size: 1.05
                    inner_size: 1.05
                    pad_size:   0.5
                    outer_line_width: 0.1
                    inner_line_width: 0.1
                    pad_line_width:   0.1
                    outer_background_color: (0.75, 0.75, 0.75, 1)
                    outer_line_color:       (0.25, 0.25, 0.25, 1)
                    inner_background_color: (0.75, 0.75, 0.75, 1)
                    inner_line_color:       (0.7,  0.7,  0.7,  1)
                    pad_background_color:   (0.4,  0.4,  0.4,  1)
                    pad_line_color:         (0.35, 0.35, 0.35, 1)
```

**EDİT 1**: I think problem ise being inside of BoxLayout and orientation problem - seems like area problem. Because If I turn BoxLayout's orientation value to "vertical", it shows me the d-pad and gives no error. You can seet that here:

```kivy
<AdminPanel>:
    BoxLayout:
        orientation: "vertical"
        md_bg_color: app.theme_cls.primary_color

        MDGridLayout:
            rows: 5
            adaptive_width: True
            md_bg_color: app.theme_cls.primary_color

            TooltipMDIconButton:
                icon: "menu-open"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Access Menu"
            TooltipMDIconButton:
                icon: "coolant-temperature"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Temperature Shield"
            TooltipMDIconButton:
                icon: "signal-off"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Jammer"
            TooltipMDIconButton:
                icon: "car-light-high"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Car Light"
            TooltipMDIconButton:
                icon: "near-me"
                pos_hint: {"center_x": .5, "center_y": .5}
                tooltip_text: "Car Engine"

        Button:
            text: "live video here"
        GridLayout:
            size_hint_x: 0.3
            rows: 2
            BoxLayout:
                orientation: "vertical"
                md_bg_color: app.theme_cls.primary_color
                ScrollView:
                    MDList:
                        OneLineIconListItem:
                            text: "%89.7"
                            IconLeftWidget:
                                icon: "battery-80"
                        OneLineIconListItem:
                            text: "23'C"
                            IconLeftWidget:
                                icon: "weather-sunny"
                        OneLineIconListItem:
                            text: "47'C"
                            IconLeftWidget:
                                icon: "car-defrost-rear"
                        OneLineIconListItem:
                            text: "W 5 m/s"
                            IconLeftWidget:
                                icon: "weather-windy"
                        OneLineIconListItem:
                            text: "70 km/h"
                            IconLeftWidget:
                                icon: "speedometer"
                        OneLineIconListItem:
                            text: "Lo: 42.784624"
                            on_release: root.coordinates()
                            IconLeftWidget:
                                icon: "longitude"
                        OneLineIconListItem:
                            text: "La: 27.473215"
                            on_release: root.coordinates()
                            IconLeftWidget:
                                icon: "latitude"
                        OneLineIconListItem:
                            text: "Al: 3481 m "
                            on_release: root.coordinates()
                            IconLeftWidget:
                                icon: "map-marker-radius"
            Joystick:
                sticky: False
                outer_size: 1.05
                inner_size: 1.05
                pad_size:   0.5
                outer_line_width: 0.01
                inner_line_width: 0.01
                pad_line_width:   0.01
                outer_background_color: (0.75, 0.75, 0.75, 1)
                outer_line_color:       (0.25, 0.25, 0.25, 1)
                inner_background_color: (0.75, 0.75, 0.75, 1)
                inner_line_color:       (0.7,  0.7,  0.7,  1)
                pad_background_color:   (0.4,  0.4,  0.4,  1)
                pad_line_color:         (0.35, 0.35, 0.35, 1)
```

**Comment by electricalgorithm** [comment]
Solved it with inserting all the <AdminPanel>'s first children into different BoxLayouts. Then set the MDGridLayout with "size_hint_max" and "size_hint_min" property.

**Comment by Narcolapser** [comment]
Glad you solved it. Sorry for not responding, it has been a busy week.
